### ISSUE TITLE
`plt.pcolormesh(X, Y, C)` for matplotlib v3+  error `Dimensions of C %s are incompatible with`

### ISSUE THREAD

**Issue by punkpony** [Erastova-group/DynDen#1]
Using matplotlib v.3 seems to have some mismatch with dimensions of `dens`
when running `ax.pcolormesh(X, Y, dens, cmap=c) `

in more generic terms: 
`C.shape == (nrows, ncols)` 
`plt.pcolormesh(X, Y, C)` 

error in the `_axes.py`
`X, Y, C, shading = self._pcolorargs(‘pcolormesh’, *args,`
` TypeError(‘Dimensions of C %s are incompatible with’`

needs fixing

**Comment by degiacom** [comment]
The commit [9e13724](https://github.com/Erastova-group/DynDen/commit/9e13724fcd6128d918a333187a5a0010e7b5d12f) by @Dameon020 should have fixed it.

**Comment by punkpony** [comment]
@Dameon020 provided a fix - thank you!
